### ISSUE TITLE
Commented closing parent breaks root-form eval

### ISSUE THREAD

**Issue by sevanteri** [Olical/conjure#246]
Firstly, I want to note that this doesn't happen when Treesitter is enabled for Conjure. Since finding that out I've moved to using it and this is not really a problem for me anymore.

Issue:

If there's a commented line with just a closing parenthesis at the end of the file, or anyway after the current form, evaluating the current root form evaluates a bit too much.

Here's some example Fennel code to test with. The comments at the end of the lines state what happens when evaluating on that line.
```
(print "foo") ; -er prints foo, bar, and 5
(print "bar") ; -er prints bar and 5
; )

(print ; -er prints 5
  ; )
  5) ; -er doesn't work at all

(print "baz") ; -er runs just this line
```

It seems that `conjure.extract.form` finds a bit too much to evaluate. Didn't get deeper than that since my Fennel/Conjure debugging skills are still a bit lacking. :smile:

**Comment by Olical** [comment]
Thanks for the report! I'm pretty sure I fixed this exact thing a while back 🤔 do you have highlighting for your comments when tree-sitter isn't enabled? I guess so, but that's what I rely on to ignore closing parens, I check if they're in comments first then ignore them if so.

I've been using tree-sitter for a while but ran into some issues in Fennel support and with vim-sexp (Clojure seems fine) so I've gone back to leaving it off for now. Glad it's working for you though!

**Comment by sevanteri** [comment]
Ah, okay that's pretty interesting. It indeed does work correctly if I disable treesitter highlighting for Fennel.

And yeah, I haven't tried vim-sexp at all, so don't know anything about possible issues with it. :P

**Comment by Olical** [comment]
Hmm I can't reproduce this in a test right now... can you reproduce this issue on the `develop` branch by any chance? I'm wondering if I accidentally fixed it by fixing something else recently in this area...

**Comment by sevanteri** [comment]
You, still happening. TS highlighting on, `:let g:conjure#extract#tree_sitter#enabled = v:false`.

```
(print 1) ; cursor here, -er
(print 2)
; )

; --------------------------------------------------------------------------------
; eval (root-form): (print 1) (print 2) ; )
; (out) 1
; (out) 2
nil

```

**Comment by Olical** [comment]
I know it's been forever, but I just reproduced this 👀

**Comment by Olical** [comment]
So if you want to use tree-sitter you NEED to either turn on `:let g:conjure#extract#tree_sitter#enabled = v:true` (which I might do by default since it'll only work if you have TS working in your buffer) _or_ you can enabled `additional_vim_regex_highlighting = true` in your TS config.

There is no other way around this. It's because when you enable TS it _disables_ the older regex highlighting, so from Conjure's perspective when it asks neovim about the current words/characters under the cursor it has zero information to go on, it's just a character. Which means I can't check if it's a comment so Conjure will walk out too far and consider commented code as valid.

For Conjure, in this setup, the entire document is unhighlighted plain text. It doesn't know what's a comment or a string!

So, the solution is to not go half way, you either:

 * Use TS highlight + Conjure's TS form extraction
 * Use regular nvim regex highlighting, no TS whatsoever
 * Enable the slower hybrid where you have TS highlighting with the older regexes also sprinkling in highlight information for older plugins / code to hook into

I think I'll enable TS extraction by default so that someone would need to go out of their way to hit this in the future. Sorry I didn't look at this sooner, too much to do and it slipped down the priorities but glad I understand it now at least.

No problem if it's a non-issue or you don't even use Conjure these days 😄
